[package]
name = "src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = "1.0"



ndarray = "0.16.1"
ndarray-rand = "0.15"
rand = "0.8"
rand_distr = "0.4"